FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY apps/worker ./apps/worker
COPY packages ./packages

WORKDIR /app

CMD ["node", "--import", "tsx", "packages/worker/src/index.ts"]
